resources:
  containers:
  - container: arm64v8-test-container
    image: electron.azurecr.io/build:arm64v8-6555a80939fb4c3ddf9343b3f140e573f40de225
    options: --shm-size 128m

jobs:
- job: Test_Arm64
  container: arm64v8-test-container
  displayName: Test Arm64 on Arm64 hardware
  timeoutInMinutes: 30
  steps:
  - template: vsts-arm-test-steps.yml
